# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0
services:
  rcdt_tests:
    image: rcdt/robotics:tests-${IMAGE_TAG}
    container_name: rcdt_tests
    runtime: nvidia
    network_mode: host
    privileged: true
    mem_limit: 6gb
    tty: true
    group_add:
      - "video" # Allows camera access on all platforms, no matter the allocated user rights
    env_file:
      - .env
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev:/dev"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/rcdt_robotics/"
    command:
      ["/bin/bash", "-c", "cd /rcdt_robotics"]
