# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0
services:
  rclone_filesync:
    container_name: rclone_filesync
    image: rclone/rclone:latest
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - $HOME/rclone.env
    volumes:
      - $HOME/.config/rclone:/config/rclone
      - $HOME/data:/data
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
