# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

# Based on: 
# https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/4.5.0/ur_robot_driver/config/ur5_update_rate.yaml

controller_manager:
  ros__parameters:
    update_rate: 125  # Hz