# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: docker

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  detect-changes:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_changes: ${{ steps.set-matrix.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changed subdirectories
        id: set-matrix
        run: |
          # TODO switch this back before pushing
          # CHANGES=rcdt_nav2/
          CHANGES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          
          COMPONENTS=$(yq -o=json '.components' components.yml | jq '[
            to_entries[] |
              .key as $name |
              if (.value | type) == "array" then
                .value[] | . + {"name": $name}
              else
                .value + {"name": $name}
              end |
              {
                "name": .name,
                "base_image": .base_image,
                "tag": .tag,
                "dockerfile": .dockerfile
              }
          ]')

          CHANGED_DIRS=()
          for d in *rcdt_* ; do
            if echo "$CHANGES" | grep -q "^${d}/"; then
              CHANGED_DIRS+=("$d")
            fi
          done
          
          echo "Changed directories: ${CHANGED_DIRS[*]}"
          
          if [ ${#CHANGED_DIRS[@]} -eq 0 ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "matrix={\"include\":[]}" >> $GITHUB_OUTPUT
            echo "No components have changes."
          else
            CHANGED_JSON=$(printf '%s\n' "${CHANGED_DIRS[@]}" | jq -R . | jq -s -c '.')
            
            MATRIX=$(echo "$COMPONENTS" | jq -c --argjson changed "$CHANGED_JSON" '
              map(select(.name as $n | $changed | index($n)))
            ')
            
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "matrix={\"include\":$MATRIX}" >> $GITHUB_OUTPUT
            echo "Changed components matrix: $MATRIX"
          fi

  build:
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Free disk space 
        uses: ./.github/actions/free-disk-space
        with:
          tool-cache: true
      - name: Clear disk space 
        uses: ./.github/actions/clear-disk-space
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push ${{ matrix.tag }}
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ${{ matrix.dockerfile }}
          tags: rcdt/robotics:${{ matrix.tag }}-amd64
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}-amd64
          cache-from: |
            type=gha
            type=registry,ref=rcdt/robotics:${{ matrix.tag }}-amd64
          cache-to: type=gha,mode=max
      - run: df -h /
  test:
    needs: [detect-changes, build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running pytests"
      - name: Run tests in rcdt_test container
        run: python3 start.py --pytest
