# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: pr

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  try-secrets:
    runs-on: ubuntu-24.04
    steps:
      - run: echo ${{ secrets.DOCKER_USERNAME }}
