# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: docker

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-realsense:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up python3
        uses: actions/setup-python@v5
        with:
          # need to specify version to circumvent externally-managed act python
          # which won't let us install dependencies
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: pip install PyYAML termcolor
      - name: build realsense image
        run: python3 image_manager.py --build -c realsense